#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

ZDOTDIR=$HOME
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#source "${ZDOTDIR:-$HOME}/git.plugin.sh"
source "${ZDOTDIR:-$HOME}/mvn.plugin.sh"

export NVM_DIR="/home/k83093/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

alias tunnels="/home/k83093/projects/tunnel/tunnel k83093"

#autoload -Uz promptinit
#promptinit
#prompt sorin
